# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e288c86e683de88bd511fcdf2e78040b"
name = "Smart Activity Tracker"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_draft_orders,read_fulfillments,read_inventory,read_locations,read_marketing_events,read_orders,read_price_rules,read_products,read_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
